#!/usr/bin/env python3
"""Derive clean prose from cms-notes-intro.tex for use as extraction context.

Keeps the section structure and the entry keys (which point at examples in
notes-test.bib), drops LaTeX scaffolding, endnote plumbing, and the
\\printbibliography calls whose output comes from notes-test.bib's annote
fields anyway.
"""
import re
import sys

src = open(sys.argv[1], encoding='utf-8').read()

# Body starts at the first real section.
src = src[src.index(r'\section{Standard entry types}'):]

# Drop full-line comments.
src = '\n'.join(l for l in src.split('\n') if not l.lstrip().startswith('%'))

# Drop the trailing "The Database File" appendix: ~60 lstlisting blocks that
# reproduce notes-test.bib entries verbatim, minus their annotations. Keeping
# them would duplicate a file already supplied in full, and the listings' URLs
# are broken mid-string by the original's column width (e.g.
# "http://www.cnn.com/1999/TECH/ ptech/12/20/implant.device/"), which is
# actively misleading as example data. The prose sections' own
# \endnote[\value{Type}]{\cite{key}} type-to-example mappings are untouched.
src = re.sub(r'\\begin\{lstlisting\}(\[[^\]]*\])?.*?\\end\{lstlisting\}', '',
             src, flags=re.DOTALL)
src = re.sub(r'\\twocolumn\[[^\]]*\]', '', src)

# \endnote[\value{Type}]{\cite{key}.} and \lnbackref{Type}{key} both encode a
# TYPE -> worked-example mapping. That is the most useful thing in the file,
# so render it rather than stripping it.
src = re.sub(r'\\endnote\[\\value\{([A-Za-z]+)\}\]\{\\cite\{([^}]*)\}\.?\}',
             r'\n- \1: [\2]', src)
src = re.sub(r'\\lnbackref\{([A-Za-z]+)\}\{([^}]*)\}', r'\1: [\2]', src)

# Remaining plumbing has no informational content.
src = re.sub(r'\\theendnotes', '', src)
src = re.sub(r'\\printbibliography(\[[^\]]*\])?', '', src)
src = re.sub(r'\{?\\renewcommand\{[^}]*\}\{[^}]*\}[^}]*\}?', '', src)
src = re.sub(r'\\(?:hyperlink|getrefbykeydefault|colorbox|color)\{[^}]*\}(\{[^}]*\})?', '', src)
src = re.sub(r'\\endnote(\[[^\]]*\])?\{.*?\}\.?,?', '', src, flags=re.DOTALL)

# Section headings -> markdown.
src = re.sub(r'\\section\{(.*?)\}', lambda m: '\n\n## ' + m.group(1).strip() + '\n', src)

# Citation keys are worth keeping: they name examples in notes-test.bib.
src = re.sub(r'\\(?:auto)?cite\*?(?:\[[^\]]*\])*\{([^}]*)\}', r'[\1]', src)
src = re.sub(r'\\cmslink\{([^}]*)\}', r'[\1]', src)

# Cross-references into biblatex-chicago.pdf: keep the field/topic name only.
src = re.sub(r'\\cmssecref\[([^\]]*)\]\{[^}]*\}', r'', src)
src = re.sub(r'\\cms(?:sec|tab)ref\{[^}]*\}', '', src)

# Inline formatting -> plain text.
for _ in range(4):
    src = re.sub(r'\\(?:textsf|emph|texttt|textbf|mkbibquote|mkbibemph)\{([^{}]*)\}',
                 r'\1', src)

# Environments and layout noise.
src = re.sub(r'\\(?:begin|end)\{[^}]*\}(\[[^\]]*\])?', '', src)
src = re.sub(r'\\(?:label|index|hypertarget|phantomsection)\{[^}]*\}', '', src)
src = re.sub(r'\\(?:mylittlespace|noindent|newpage|clearpage|bigskip|medskip|smallskip|par)\b', '', src)
src = re.sub(r'\\cmd\{([^}]*)\}', r'\\\1', src)

# Late-stage macro cleanup. Brace-matched removal handles nesting.
def drop_cmd(text, names, keep_arg=False):
    pat = re.compile(r'\\(?:' + '|'.join(names) + r')\*?\{')
    while True:
        m = pat.search(text)
        if not m: return text
        i, depth = m.end(), 1
        while i < len(text) and depth:
            if text[i] == '{': depth += 1
            elif text[i] == '}': depth -= 1
            i += 1
        text = text[:m.start()] + (text[m.end():i-1] if keep_arg else '') + text[i:]

src = drop_cmd(src, ['footnote', 'vspace', 'twocolumn', 'enlargethispage'])
src = drop_cmd(src, ['headlesscite', 'fullcite', 'citejournal', 'textcite',
                     'surnamecite', 'shortcite', 'textsc'], keep_arg=True)
import unicodedata
src = re.sub(r"\\c\{([A-Za-z])\}",
             lambda m: unicodedata.normalize('NFC', m.group(1) + '\u0327'), src)

# Late-stage macro cleanup.
src = re.sub(r'\\(?:footnote|enlargethispage|baselineskip|setlength)\{[^{}]*\}', '', src)
src = re.sub(r'\\(?:textsc|textcite|surnamecite|shortcite)\{([^{}]*)\}', r'\1', src)
src = src.replace(r'\TeX', 'TeX').replace(r'\LaTeX', 'LaTeX')

# Remaining bare macros with no argument we care about.
src = re.sub(r'\\[a-zA-Z@]+\*?(\[[^\]]*\])?\{\}', '', src)
src = re.sub(r'\\(?:autocap|bibstring)\{([^}]*)\}', r'\1', src)

# Escapes and ligatures.
src = (src.replace(r'\&', '&').replace(r'\%', '%').replace(r'\_', '_')
          .replace(r'\#', '#').replace('~', ' ').replace('---', '—').replace('--', '-'))
src = re.sub(r'\\ (?=\w)', ' ', src)
src = re.sub(r'\\\\', '\n', src)

# Whitespace normalisation: collapse runs, keep paragraph breaks.
src = re.sub(r'[ \t]+', ' ', src)
src = re.sub(r' *\n *', '\n', src)
src = re.sub(r'\n{3,}', '\n\n', src)
src = re.sub(r' ([,.;:)])', r'\1', src)

header = (
    "# The Chicago Notes & Bibliography Specification: entry-type guide\n\n"
    "DERIVED WORK. Generated by `extract_intro.py` from `cms-notes-intro.tex`\n"
    "in the biblatex-chicago package (v2.3b), Copyright (c) 2008-2024 David\n"
    "Fussner, licensed under the LaTeX Project Public License (LPPL) v1.3.\n"
    "LaTeX scaffolding has been stripped and the type/example cross-references\n"
    "rendered as plain text; no wording was otherwise changed.\n\n"
    "Explains which entry TYPE to choose for a given kind of source. Names in\n"
    "[brackets] are entry keys of worked examples in `notes-test.bib`.\n"
    "NB this reflects the package's own house style, which departs from this\n"
    "project's conventions in places; CLAUDE.md takes precedence.\n"
)
open(sys.argv[2], 'w', encoding='utf-8').write(header + src.strip() + '\n')
print(f"wrote {sys.argv[2]}")
