#!/usr/bin/env python3
"""Rebuild `prompt-context/biblio-template.bib` from real entries in biblio.bib.

The template is both the house-style exemplar loaded into every extraction
prompt and the regression fixture: `bib_normalize.py` must report 0 edits
against it, and it must compile without biber warnings.

Drawing it from the live library rather than inventing data means the examples
are real, already conform to whatever the rules currently say, and stay in step
when the rules change -- rerun this and diff. Bookkeeping fields are stripped:
they belong to BibDesk and DEVONthink, not to the bibliographic record.

    python3 dev/build_template.py ~/Documents/Bibdesk/biblio.bib -o out.bib
"""

from __future__ import annotations

import argparse
import os
import re
import sys
import textwrap

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from bib_audit import scan  # noqa: E402

# One entry per type, chosen so that between them they exercise every
# construct that has caused trouble in this project.
PICKS = [
    ("Marvin2012", "Generic article",
     "Date as an ISO 8601-2 range (solidus); Volume as an en-dash range; "
     "Title/Subtitle split; nested \\mkbibemph, \\mkbibquote and "
     "\\foreignlanguage; Pages with a single hyphen."),
    ("Czerny1839", "Book",
     "Earned Shorttitle: the title carries TWO top-level colons, so which is "
     "the entry's own boundary is ambiguous and the splitter declines. Url "
     "kept because there is no Doi."),
    ("Tan2023", "Chapter within a book",
     "Doi present, therefore no Url; Title/Subtitle split; Pages with a "
     "single hyphen."),
    ("Marston2001", "Article in a reference work",
     "Online reference work: Entrysubtype, Url and Urldate are required "
     "together. The work goes in Title, the article in Lista."),
    ("SchumannSchenkerBittendes", "Miscellaneous item",
     "\\foreignlanguage wrapping a whole non-name field; \\mkbibquote; "
     "Langid; Entrysubtype."),
    ("Johansen2018", "Musical score",
     "Series carries the series name alone; the division that the imprint "
     "page attaches to it goes in Number, which is what makes the punctuation "
     "between the two come out right."),
    ("Deliege2009", "Online-only source",
     "A title whose colon is sealed inside \\foreignlanguage: the splitter "
     "declines it, so the split was made by hand and BOTH halves carry their "
     "own wrapper. Shorttitle then falls away. Url and Urldate, which an "
     "Online entry must carry."),
    ("Sofer2025", "Whole issue of a periodical",
     "Number as an en-dash range -- a literal field, so the separator typed "
     "is the one that reaches the page; Issuetitle."),
    ("Vasdekis", "Reference work cited as a whole",
     "Earned Shorttitle via a sealed colon, in Greek; name components wrapped "
     "individually so the editor still inverts."),
    ("Gollin2011a", "Introduction, preface or afterword to a book",
     "Bookauthor distinct from Author; Pages."),
    ("Hampe", "Introduction, preface or afterword to a collection",
     "Editora with Editoratype; Title/Subtitle split."),
    ("Aleksandrova2015", "Book, second example -- foreign name components",
     "Both Author and Editor have every name component wrapped separately, so "
     "biber still parses surname from forenames and the editor inverts. "
     "Editortype and Series are wrapped as whole fields, which is correct for "
     "non-name fields."),
    ("Argerich2008", "Video recording",
     "Type; Editortype; Origdate beside Date; Langid."),
]

# BibDesk and DEVONthink bookkeeping, plus the fields the guidelines forbid.
DROP = re.compile(
    r"^(bdsk-file|bdsk-url|local-url|remote-url|devonthink|date-added|"
    r"date-modified|keywords|rating|read|reference)")

HEADER = """\
% Minimal BibLaTeX-Chicago template.
% One example per entry type, showing the fields that type takes.
%
% Generated by dev/build_template.py from real entries in biblio.bib, stripped
% of BibDesk and DEVONthink bookkeeping (bdsk-file, bdsk-url, local-url,
% remote-url, devonthink, date-added, date-modified, rating, read, reference)
% and of the fields the guidelines forbid (keywords).
%
% This file doubles as the regression fixture: bib_normalize.py must report
% 0 edits against it, and it must compile without biber warnings. Rerun the
% generator after a rule change and diff.
%
% NOTE: avoid the at-sign in these comments. A BibTeX parser reads it as the
% start of an entry even on a comment line.
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("source")
    ap.add_argument("-o", "--out", required=True)
    args = ap.parse_args()

    entries = {e.citekey: e
               for e in scan(open(args.source, "rb").read().decode("utf-8"))[0]}
    missing = [ck for ck, _, _ in PICKS if ck not in entries]
    if missing:
        print(f"ABORT: not in {args.source}: {missing}")
        return 1

    out = [HEADER]
    for citekey, heading, why in PICKS:
        e = entries[citekey]
        out.append(f"% --- {heading} ---")
        for line in textwrap.wrap(why, 74):
            out.append(f"% {line}")
        out.append(f"@{e.etype}{{{citekey},")
        for f in e.fields:
            if DROP.match(f.key):
                continue
            name = f.key[:1].upper() + f.key[1:]
            out.append(f"\t{name} = {{{f.value}}},")
        out.append("}")
        out.append("")

    text = "\n".join(out)
    if "@" in "\n".join(ln for ln in text.split("\n") if ln.startswith("%")):
        print("ABORT: an at-sign reached a comment line")
        return 1

    with open(args.out, "wb") as fh:
        fh.write(text.encode("utf-8"))
    print(f"wrote {len(PICKS)} entries to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
